config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    #注文詳細
    resources :order_details, only: [:update]
    #注文
    resources :orders, only: [:show, :update]
    #会員
    resources :customers, only: [:show, :edit, :index, :update]
    #ジャンル
    resources :genres, only: [:create, :edit, :index, :update]
    #商品
    resources :items, only: [:show, :edit, :index, :update, :new, :create]
    #ホーム画面
    get '/' => 'homes#top'
  end
  scope module: :public do
    #配送先
    resources :addresses, only: [:destroy, :edit, :index, :update, :create]
    #注文
    post 'orders/confirm'
    get 'orders/thanx'
    resources :orders, only: [:show, :index, :new, :create]
    #カート内商品
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete 'cart_items' => 'cart_items#all_destroy'
    #商品
    resources :items, only: [:show, :index]
    #会員
    get '/customers', to: 'customers#show'
    get '/customers/informetion/edit', to: 'customers#edit'
    patch '/customers/informetion', to: 'customers#update', as: 'update_informetion'
    get 'customers/quit'
    patch 'customers/out'
    #ホーム画面
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
   '〒' + postcode + ' ' + addresses + ' ' + name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def address_display
   '〒' + postcode + ' ' + address + ' ' + last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  validates :price, :name, presence: true

  def add_tax_price
    (price * 1.10).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_production: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, sent: 4 }

  def address_display
   '〒' + postcode + ' ' + address + ' ' + name
  end

  def subtotal
    item.add_tax_price*quantity
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { cannot_start: 0, waiting_for_production: 1,
  in_production: 2, completion_of_production: 3 }
  
  def subtotal
    item.add_tax_price*quantity
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :genre_id, :image, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
    # @order_details = @order.order_details
    # @order_details.update(order_detail_params)
  end

  private

  def order_params
      params.require(:order).permit(:status)
  end

  def order_detail_params
      params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    root_path
  end
end

def after_sign_out_path_for(resource)
  root_path
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
<%= form_with model: @item, url: admin_item_path do |f| %>
  <div class="form-group">
    <%= f.label :商品画像 %>
    <%= f.file_field :image, accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.label :商品名 %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :商品説明 %>
    <%= f.text_area :explanation %>
  </div>
  <div class="form-group">
    <%= f.label :ジャンル %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :税抜価格 %>
    <%= f.number_field :price %>円
  </div>
  <div class="form-group">
    <td>販売ステータス</td>
    <%= f.label :販売中 %>
    <%= f.radio_button :is_active, true %>
    <%= f.label :販売停止中 %>
    <%= f.radio_button :is_active, false %>
  </div>
  <div class="form-group">
    <%= f.submit '変更を保存', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/items/index.html.erb
<div class='container m-5'>
  <h1>商品一覧</h1>
  <div>
    <%= link_to '商品を追加する', new_admin_item_path, class: "float-right btn btn-primary" %>
  </div>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id), class: "text-dark border-bottom" %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<div class='container m-5'>
  <h1>商品新規登録</h1>
  <form class="form-horizontal">
  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="form-group">
      <%= f.label :商品画像, class: "col-2 control-label" %>
      <%= f.file_field :image, accept: "image/*", class: "col-3" %>
    </div>
    <div class="form-group">
      <%= f.label :商品名, class: "col-2 control-label" %>
      <%= f.text_field :name, placeholder: '商品名', class: "col-3" %>
    </div>
    <div class="form-group">
      <%= f.label :商品説明, class: "col-2 control-label" %>
      <%= f.text_area :explanation, placeholder: 'ここに説明文を記述します', class: "col-3" %>
    </div>
    <div class="form-group">
      <%= f.label :ジャンル, class: "col-2 control-label" %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "--選択してください--"}, class: "col-3" %>
    </div>
    <div class="form-group">
      <%= f.label :税抜価格, class: "col-2 control-label" %>
      <%= f.number_field :price, placeholder: '1000', class: "col-3" %>円
    </div>
    <div class="form-group">
      <td class="mr-1">販売ステータス</td>
      <%= f.label :販売中 %>
      <%= f.radio_button :is_active, true %>
      <%= f.label :販売停止中 %>
      <%= f.radio_button :is_active, false %>
    </div>
    <div class="form-group">
      <%= f.submit '新規登録', class: 'btn btn-success' %>
    </div>
  <% end %>
  </form>
</div>

app/views/admin/items/show.html.erb
<div class='container m-5'>
  <h1>商品詳細</h1>
  <div class="row">
    <div class="col-5">
      <%= image_tag @item.get_image(300,300) %>
    </div>
    <div>
      <form class="form-horizontal">
        <p>
          <span class="mr-3 font-weight-bold">商品名 </span><%= @item.name %>
        </p>
        <p>
          <span class="mr-3 font-weight-bold">商品説明 </span><%= @item.explanation %>
        </p>
        <p>
          <span class="mr-3 font-weight-bold">ジャンル </span><%= @item.genre.name %>
        </p>
        <p>
          <span class="mr-3 font-weight-bold">税込価格 </br>（税抜価格）</span> <%= @item.price %> (<%= @item.add_tax_price.to_s %>)円
        </p>
        <p>
          <span class="mr-3 font-weight-bold">販売ステータス</span><%= @item.is_active ? '販売中' : '販売停止中' %>
        </p>
      </form>
      <p>
        <%= link_to '編集する', edit_admin_item_path(@item.id), class: 'btn btn-success' %>
      </p>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container m-5">
  <h1>注文履歴詳細</h1>
  <table>
    <tr>
      <th>購入者</th>
      <td><%= @order.name %></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td><%= @order.address %></td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
        <%= form_with model: @order, url: admin_order_path do |f| %>
          <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          <%= f.submit '更新', class: 'btn btn-success' %>
        <% end %>
      </td>
    </tr>
  </table>
  
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>商品名</th>
        <th>単価（税込）</th>
        <th>数量</th>
        <th>小計</th>
        <th>制作ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @sum = 0 %>
      <% @order_details.each do |order_details| %>
        <% @sum += order_details.subtotal %>
        <tr>
          <td><%= order_details.item.name %></td>
          <td><%= order_details.price %></td>
          <td><%= order_details.quantity %></td>
          <td><%= order_details.subtotal %></td>
          <td>
            <%= form_with model: order_details, url: admin_order_detail_path(order_details) do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
              <%= f.submit '更新', class: 'btn btn-success' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <table>
    <tr>
      <th>商品合計</th>
      <td><%= @sum %>円</td>
    </tr>
    <tr>
      <th>送料</th>
      <td><%= @order.postage %>円</td>
    </tr>
    <tr>
      <th>請求金額合計</th>
      <td><%= @order.billing_amount %>円</td>
    </tr>
  </table>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>