config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    #注文詳細
    resources :order_details, only: [:update]
    #注文
    resources :orders, only: [:show, :update]
    #会員
    resources :customers, only: [:show, :edit, :index, :update]
    #ジャンル
    resources :genres, only: [:create, :edit, :index, :update]
    #商品
    resources :items, only: [:show, :edit, :index, :update, :new, :create]
    #ホーム画面
    get '/' => 'homes#top'
  end
  scope module: :public do
    #配送先
    resources :addresses, only: [:destroy, :edit, :index, :update, :create]
    #注文
    post 'orders/confirm'
    get 'orders/thanx'
    resources :orders, only: [:show, :index, :new, :create]
    #カート内商品
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete 'cart_items' => 'cart_items#all_destroy'
    #商品
    resources :items, only: [:show, :index]
    #会員
    get '/customers', to: 'customers#show'
    get '/customers/informetion/edit', to: 'customers#edit'
    patch '/customers/informetion', to: 'customers#update', as: 'update_informetion'
    get 'customers/quit'
    patch 'customers/out'
    #ホーム画面
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
   '〒' + postcode + ' ' + addresses + ' ' + name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def address_display
   '〒' + postcode + ' ' + address + ' ' + last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  validates :price, :name, presence: true

  def add_tax_price
    (price * 1.10).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_production: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, sent: 4 }

  def address_display
   '〒' + postcode + ' ' + address + ' ' + name
  end

  def subtotal
    item.add_tax_price*quantity
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { cannot_start: 0, waiting_for_production: 1,
  in_production: 2, completion_of_production: 3 }
  
  def subtotal
    item.add_tax_price*quantity
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
 
  end

  def show
    @customer = Customer.find(params[:id])
  end
    
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end
  
  private

  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name,
    :last_name_kana, :first_name_kana, :postcode, :address,
    :phone_number, :is_deleted
    )
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :genre_id, :image, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
    # @order_details = @order.order_details
    # @order_details.update(order_detail_params)
  end

  private

  def order_params
      params.require(:order).permit(:status)
  end

  def order_detail_params
      params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    root_path
  end
end

def after_sign_out_path_for(resource)
  root_path
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="m-5">
    <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    <%= form_with model: @customer,url: admin_customer_path(@customer.id), local:true do |f| %>
    <form class="form-horizontal">
      <div class="form-group">
        <p class="col-2 control-label">会員ID<%= @customer.id %></p>
      </div>
      <div class="form-group">
            <%= f.label :氏名, class: "col-2 control-label" %>
            <%= f.text_field :last_name, class: "col-3" %>
            <%= f.text_field :first_name, class: "col-3" %>
      </div>
      <div class="form-group">
            <%= f.label :フリガナ, class: "col-2 control-label"  %>
            <%= f.text_field :last_name_kana, class: "col-3" %>
            <%= f.text_field :first_name_kana, class: "col-3" %>
      </div>
      <div class="form-group">
            <%= f.label :郵便番号, class: "col-2 control-label" %>
            <%= f.text_field :postcode, class: "col-3" %>
      </div>
      <div class="form-group">
            <%= f.label :住所, class: "col-2 control-label" %>
            <%= f.text_field :address, class: "col-3" %>
      </div>
      <div class="form-group">
            <%= f.label :電話番号, class: "col-2 control-label" %>
            <%= f.text_field :phone_number, class: "col-3" %>
      </div>
      <div class="form-group">
            <%= f.label :メールアドレス, class: "col-2 control-label" %>
            <%= f.text_field :email, class: "col-3" %>
      </div>
      <div class="form-group">
            <span class="col-2 control-label">会員ステータス </span>
            <span class="col-3">
            <%= f.label :有効 %>
            <%= f.radio_button :is_deleted,false %>
            <%= f.label :退会 %>
            <%= f.radio_button :is_deleted,true %>
            </span>
      </div>
      </form>
      <div class="form-group">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container m-5">
  <h4 class="font-weight-bold bg-info">会員一覧</h4>
  <div class="row">
    <table class='table'>
      <thead>
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
           <tr>
             <td class="text-dark"><%= customer.id %></td>
             <td><%= link_to admin_customer_path(customer.id) do %>
               <%=  customer.last_name %><%= customer.first_name %>
               <% end %>
               </td>
             <td><%= customer.email %></td>
             <td class="text-success font-weight-bold"><%= customer.is_deleted ? '退会' : '有効'%></td>
           </tr>
        <% end %>
        <%= paginate @customers %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class='container m-5'>
  <div class='row'>
    <div class='col-md-8 offset-md-1'>
      <div class="font-weight-bold bg-info"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</div>
        <table style="line-height:3rem">
         <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td class="text-success font-weight-bold"><%= @customer.is_deleted ? '退会' : '有効'%></td>
        </tr>
      </table>
      <div class="text-center">
        <%= link_to "編集する",edit_admin_customer_path(@customer.id), class: "btn btn-success" %>
        <%= link_to "注文履歴一覧をみる",admin_path , class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>