config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    #注文詳細
    resources :order_details, only: [:update]
    #注文
    resources :orders, only: [:show, :update]
    #会員
    resources :customers, only: [:show, :edit, :index, :update]
    #ジャンル
    resources :genres, only: [:create, :edit, :index, :update]
    #商品
    resources :items, only: [:show, :edit, :index, :update, :new, :create]
    #ホーム画面
    get '/' => 'homes#top'
  end
  scope module: :public do
    #配送先
    resources :addresses, only: [:destroy, :edit, :index, :update, :create]
    #注文
    post 'orders/confirm'
    get 'orders/thanx'
    resources :orders, only: [:show, :index, :new, :create]
    #カート内商品
    resources :cart_items, only: [:index, :update, :destroy, :create]
    delete 'cart_items' => 'cart_items#all_destroy'
    #商品
    resources :items, only: [:show, :index]
    #会員
    get '/customers', to: 'customers#show'
    get '/customers/informetion/edit', to: 'customers#edit'
    patch '/customers/informetion', to: 'customers#update', as: 'update_informetion'
    get 'customers/quit'
    patch 'customers/out'
    #ホーム画面
    root to: 'homes#top'
    get '/about' => 'homes#about'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
   '〒' + postcode + ' ' + addresses + ' ' + name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses
  has_many :cart_items
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def address_display
   '〒' + postcode + ' ' + address + ' ' + last_name  + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details

  has_one_attached :image

  validates :price, :name, presence: true

  def add_tax_price
    (price * 1.10).floor
  end

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_production: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, sent: 4 }

  def address_display
   '〒' + postcode + ' ' + address + ' ' + name
  end

  def subtotal
    item.add_tax_price*quantity
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { cannot_start: 0, waiting_for_production: 1,
  in_production: 2, completion_of_production: 3 }
  
  def subtotal
    item.add_tax_price*quantity
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :genre_id, :image, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  case resource
  when Admin
    admin_path
  when Customer
    root_path
  end
end

def after_sign_out_path_for(resource)
  root_path
end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>長野ケーキ</span></a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if customer_signed_in? %>
      <li>
        <%= link_to "マイページ", customers_path %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path %>
      </li>
      <li>
        <%= link_to "カート", cart_items_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
      </li>
    <% elsif admin_signed_in? %>
      <li>
        <%= link_to "商品一覧", admin_items_path %>
      </li>
      <li>
        <%= link_to "会員一覧", admin_customers_path %>
      </li>
      <li>
          <%= link_to "注文履歴一覧", admin_path %>
      </li>
      <li>
        <%= link_to "ジャンル一覧", admin_genres_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "商品一覧", items_path %>
      </li>
      <li>
        <%= link_to "新規登録", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_customer_session_path %>
      </li>
    <% end %>
    </ul>
    </div>
    </div>
    <% if customer_signed_in? %>
    <div class="navbar-brand mx-auto" style="width: 200px;">
      <h6>ようこそ、<%= current_customer.last_name%>さん！</h6>
    </div>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NAGANOcake</title>



    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>